version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - python/test
      - run:
          name: Run Tests
          command: pytest --cov
          environment:
            CODECOV_TOKEN: $CodeCov_Token

      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

workflows:
  main:
    jobs:
      - build-and-test
