version: 2.1
jobs:
  build_and_test:
    executor: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  build:
    jobs:
      - build_and_test