version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - python/test
      - run:
          override:
            - pytest --cov=pyTest,timer_unitTest

      - run:
          name: Upload coverage report to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t $CodeCov_Token

workflows:
  main:
    jobs:
      - build-and-test
