version : 2.1

orbs: 
  python: circleci/python@0.3.2
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    executor : python/default
    steps:
      - checkout
      - python/install-deps
      - python/test
      - run:
          name: Run Tests
          command: pytest --cov
      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f coverage.xml

workflows:
  main:
    jobs:
    - build-and-test
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload


