version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Install xvfb and dependencies
          command: |
            sudo apt-get update
            sudo apt-get install xvfb -y
            pip install xvfbwrapper

      - run:
          name: Set up virtual display
          command: |
            Xvfb :99 -screen 0 1024x768x24 &
            export DISPLAY=:99

      - run:
          name: Run Tests
          command: python -m unittest /home/circleci/project/test_timer.py # Replace <path_to_test_file> with the actual path to your test file

      - run:
          name: Run pytest for code coverage
          command: pytest --cov
          environment:
            CODECOV_TOKEN: $CodeCov_Token

      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

workflows:
  main:
    jobs:
      - build-and-test
